export default {
  logo: <span style={{ fontWeight: 700 }}>Shlink Demo</span>,
  project: {
    link: 'https://github.com/Jolli-sample-repos/shlink-demo',
  },
  docsRepositoryBase: 'https://github.com/Jolli-sample-repos/shlink-demo',
  editLink: {
    component: null,
  },
  feedback: {
    content: null,
  },
  sidebar: {
    defaultMenuCollapseLevel: 2,
  },
  toc: {
    title: 'On This Page',
  },
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta property="og:title" content="Shlink Demo" />
      <meta property="og:description" content="Documentation for Shlink Demo" />
      <style>{`:root { --nextra-primary-hue: 212deg; }`}</style>
    </>
  ),
  darkMode: true,
  nextThemes: {
    defaultTheme: 'system',
  },
  footer: {
    text: 'Shlink Demo · Generated by Jolli',
  },
  useNextSeoProps() {
    return {
      titleTemplate: '%s – Shlink Demo'
    }
  }
}
